import { defineDynamic } from "eve/skills";

import {
  resolveIntegrationSkills,
  type IntegrationSkillDefinition,
} from "../../../lib/policy/skill-catalog.ts";
import artifactsDoc from "../lib/skill_defs/artifacts.md" with { type: "text" };
import deploymentsDoc from "../lib/skill_defs/deployments.md" with { type: "text" };
import domainsDoc from "../lib/skill_defs/domains.md" with { type: "text" };
import edgePlatformDoc from "../lib/skill_defs/edge-platform.md" with { type: "text" };
import integrationsDoc from "../lib/skill_defs/integrations.md" with { type: "text" };
import observabilityDoc from "../lib/skill_defs/observability.md" with { type: "text" };
import projectsDoc from "../lib/skill_defs/projects.md" with { type: "text" };
import rolloutsDoc from "../lib/skill_defs/rollouts.md" with { type: "text" };
import sandboxesDoc from "../lib/skill_defs/sandboxes.md" with { type: "text" };
import securityDoc from "../lib/skill_defs/security.md" with { type: "text" };
import teamAdminDoc from "../lib/skill_defs/team-admin.md" with { type: "text" };

export const VERCEL_BASE_TOOL_NAMES = [
  "list_projects",
  "get_project",
  "list_deployments",
  "get_deployment",
  "list_aliases",
  "list_domains",
  "whoami",
  "list_teams",
] as const;

export const VERCEL_SKILL_DEFINITIONS = [
  {
    name: "artifacts",
    minRole: "organizer",
    doc: artifactsDoc,
    tools: ["artifacts_status", "artifact_exists", "artifact_query"],
  },
  {
    name: "deployments",
    minRole: "organizer",
    doc: deploymentsDoc,
    tools: [
      "list_deployments",
      "get_deployment",
      "get_deployment_events",
      "list_deployment_files",
      "get_deployment_file_contents",
      "cancel_deployment",
      "delete_deployment",
      "update_integration_deployment_action",
      "promote_deployment",
      "rollback_deployment",
      "update_rollback_description",
    ],
  },
  {
    name: "domains",
    minRole: "organizer",
    doc: domainsDoc,
    tools: [
      "list_aliases",
      "get_alias",
      "list_deployment_aliases",
      "assign_alias",
      "delete_alias",
      "list_domains",
      "get_domain",
      "get_domain_config",
      "delete_domain",
      "list_dns_records",
      "remove_dns_record",
      "list_supported_tlds",
      "check_domain_availability",
      "get_domain_price",
      "get_domain_auth_code",
      "get_domain_transfer_in_status",
      "get_registrar_order",
      "get_cert",
      "issue_cert",
      "remove_cert",
    ],
  },
  {
    name: "edge-platform",
    minRole: "organizer",
    doc: edgePlatformDoc,
    tools: [
      "list_global_configs",
      "get_global_config",
      "create_global_config",
      "update_global_config",
      "delete_global_config",
      "list_global_config_items",
      "get_global_config_item",
      "patch_global_config_items",
      "get_global_config_schema",
      "delete_global_config_schema",
      "list_global_config_tokens",
      "get_global_config_token",
      "create_global_config_token",
      "delete_global_config_tokens",
      "list_global_config_backups",
      "get_global_config_backup",
      "invalidate_edge_cache_by_tags",
      "dangerously_delete_edge_cache_by_tags",
      "invalidate_edge_cache_by_src_images",
      "dangerously_delete_edge_cache_by_src_images",
      "list_flags",
      "get_flag",
      "delete_flag",
      "list_flag_versions",
      "get_flag_settings",
      "list_team_flag_settings",
      "list_team_flags",
      "list_flag_segments",
      "get_flag_segment",
      "delete_flag_segment",
      "get_deployment_feature_flags",
      "list_sdk_keys",
      "create_sdk_key",
      "delete_sdk_key",
    ],
  },
  {
    name: "integrations",
    minRole: "organizer",
    doc: integrationsDoc,
    tools: [
      "list_integration_configurations",
      "get_integration_configuration",
      "get_integration_configuration_products",
      "get_integration_billing_plans",
      "delete_integration_configuration",
      "create_integration_store_direct",
      "connect_integration_resource_to_project",
      "list_integration_resources",
      "get_integration_resource",
      "delete_integration_resource",
      "list_git_namespaces",
      "search_git_repos",
    ],
  },
  {
    name: "observability",
    minRole: "organizer",
    doc: observabilityDoc,
    tools: [
      "get_runtime_logs",
      "list_log_drains",
      "get_log_drain",
      "delete_configurable_log_drain",
      "list_integration_log_drains",
      "delete_integration_log_drain",
      "list_drains",
      "get_drain",
      "delete_drain",
      "get_observability_config",
      "update_observability_config",
      "list_user_events",
      "list_event_types",
    ],
  },
  {
    name: "projects",
    minRole: "organizer",
    doc: projectsDoc,
    tools: [
      "list_projects",
      "get_project",
      "delete_project",
      "pause_project",
      "unpause_project",
      "create_project_transfer_request",
      "list_project_env_vars",
      "get_project_env_var",
      "create_project_env_vars",
      "edit_project_env_var",
      "remove_project_env_var",
      "list_project_domains",
      "get_project_domain",
      "remove_project_domain",
      "verify_project_domain",
      "list_promote_aliases",
      "list_project_members",
      "remove_project_member",
    ],
  },
  {
    name: "rollouts",
    minRole: "organizer",
    doc: rolloutsDoc,
    tools: [
      "get_rolling_release",
      "get_rolling_release_config",
      "get_rolling_release_billing_status",
      "delete_rolling_release_config",
      "approve_rolling_release_stage",
      "complete_rolling_release",
      "list_project_checks",
      "get_project_check",
      "delete_project_check",
      "list_check_runs",
      "list_deployment_check_runs",
      "get_deployment_check_run",
    ],
  },
  {
    name: "sandboxes",
    minRole: "organizer",
    doc: sandboxesDoc,
    tools: [
      "list_sandboxes",
      "get_sandbox",
      "stop_sandbox",
      "extend_sandbox_timeout",
      "list_sandbox_commands",
      "get_sandbox_command",
      "get_sandbox_command_logs",
      "kill_sandbox_command",
      "list_sandbox_snapshots",
      "get_sandbox_snapshot",
      "delete_sandbox_snapshot",
    ],
  },
  {
    name: "security",
    minRole: "organizer",
    doc: securityDoc,
    tools: [
      "get_firewall_config",
      "get_active_attack_status",
      "update_attack_challenge_mode",
      "list_bypass_ips",
      "list_firewall_events",
      "list_auth_tokens",
      "get_auth_token",
      "delete_auth_token",
    ],
  },
  {
    name: "team-admin",
    minRole: "organizer",
    doc: teamAdminDoc,
    tools: [
      "get_team",
      "list_team_members",
      "remove_team_member",
      "delete_team_invite_code",
      "list_access_groups",
      "get_access_group",
      "delete_access_group",
      "list_access_group_members",
      "list_webhooks",
      "get_webhook",
      "delete_webhook",
      "list_project_routes",
      "list_project_route_versions",
      "list_connect_networks",
      "get_connect_network",
      "delete_connect_network",
      "list_microfrontend_groups",
      "list_billing_charges",
      "list_contract_commitments",
      "list_custom_environments",
      "get_custom_environment",
      "remove_custom_environment",
    ],
  },
] as const satisfies readonly IntegrationSkillDefinition[];

export default defineDynamic({
  events: {
    "turn.started": (_event, ctx) =>
      resolveIntegrationSkills(ctx.session.auth.current, VERCEL_SKILL_DEFINITIONS),
  },
});
