import type { DomainToolSpec } from "../../../lib/policy/domain-tools.ts";
import * as m_actions from "./actions.ts";
import * as m_base from "./base.ts";
import * as m_collaborators from "./collaborators.ts";
import * as m_contents from "./contents.ts";
import * as m_deployments from "./deployments.ts";
import * as m_environments from "./environments.ts";
import * as m_issues from "./issues.ts";
import * as m_membership from "./membership.ts";
import * as m_organization from "./organization.ts";
import * as m_packages from "./packages.ts";
import * as m_projects from "./projects.ts";
import * as m_pull_requests from "./pull-requests.ts";
import * as m_reactions from "./reactions.ts";
import * as m_releases from "./releases.ts";
import * as m_repositories from "./repositories.ts";
import * as m_secrets_and_variables from "./secrets-and-variables.ts";
import * as m_tags_refs from "./tags-refs.ts";

export const GITHUB_TOOLS = {
  add_assignees: m_issues.add_assignees,
  add_collaborator: m_collaborators.add_collaborator,
  add_comment_reaction: m_reactions.add_comment_reaction,
  add_issue_reaction: m_reactions.add_issue_reaction,
  add_member_to_platform: m_membership.add_member_to_platform,
  add_team_member: m_organization.add_team_member,
  archive_repository: m_repositories.archive_repository,
  cancel_repo_invitation: m_collaborators.cancel_repo_invitation,
  cancel_workflow_run: m_actions.cancel_workflow_run,
  close_pull_request: m_pull_requests.close_pull_request,
  compare_commits: m_contents.compare_commits,
  create_deployment: m_deployments.create_deployment,
  create_deployment_status: m_deployments.create_deployment_status,
  create_issue: m_issues.create_issue,
  create_issue_comment: m_issues.create_issue_comment,
  create_or_update_environment: m_environments.create_or_update_environment,
  create_or_update_file: m_contents.create_or_update_file,
  create_or_update_org_secret: m_secrets_and_variables.create_or_update_org_secret,
  create_or_update_org_variable: m_secrets_and_variables.create_or_update_org_variable,
  create_or_update_repo_secret: m_secrets_and_variables.create_or_update_repo_secret,
  create_or_update_repo_variable: m_secrets_and_variables.create_or_update_repo_variable,
  create_pr_review: m_pull_requests.create_pr_review,
  create_project_item: m_projects.create_project_item,
  create_pull_request: m_pull_requests.create_pull_request,
  create_ref: m_tags_refs.create_ref,
  create_release: m_releases.create_release,
  create_repository: m_repositories.create_repository,
  create_webhook: m_organization.create_webhook,
  delete_branch_protection: m_repositories.delete_branch_protection,
  delete_environment: m_environments.delete_environment,
  delete_file: m_contents.delete_file,
  delete_issue_comment: m_issues.delete_issue_comment,
  delete_org_secret: m_secrets_and_variables.delete_org_secret,
  delete_org_variable: m_secrets_and_variables.delete_org_variable,
  delete_package_version: m_packages.delete_package_version,
  delete_project_item: m_projects.delete_project_item,
  delete_ref: m_tags_refs.delete_ref,
  delete_release: m_releases.delete_release,
  delete_repo_secret: m_secrets_and_variables.delete_repo_secret,
  delete_repo_variable: m_secrets_and_variables.delete_repo_variable,
  delete_repository: m_repositories.delete_repository,
  delete_webhook: m_organization.delete_webhook,
  download_artifact: m_actions.download_artifact,
  get_branch_protection: m_repositories.get_branch_protection,
  get_commit: m_contents.get_commit,
  get_directory_tree: m_contents.get_directory_tree,
  get_environment: m_environments.get_environment,
  get_file_content: m_contents.get_file_content,
  get_org_member: m_organization.get_org_member,
  get_package: m_packages.get_package,
  get_pages_info: m_deployments.get_pages_info,
  get_project: m_projects.get_project,
  get_ref: m_tags_refs.get_ref,
  get_release: m_releases.get_release,
  get_repository: m_base.get_repository,
  get_team: m_organization.get_team,
  get_workflow_run: m_actions.get_workflow_run,
  invite_org_member: m_organization.invite_org_member,
  list_branches: m_repositories.list_branches,
  list_collaborators: m_collaborators.list_collaborators,
  list_commits: m_contents.list_commits,
  list_deployments: m_deployments.list_deployments,
  list_environments: m_environments.list_environments,
  list_issue_comments: m_issues.list_issue_comments,
  list_org_members: m_organization.list_org_members,
  list_org_projects: m_projects.list_org_projects,
  list_org_secrets: m_secrets_and_variables.list_org_secrets,
  list_org_variables: m_secrets_and_variables.list_org_variables,
  list_org_webhooks: m_organization.list_org_webhooks,
  list_package_versions: m_packages.list_package_versions,
  list_packages: m_packages.list_packages,
  list_pages_builds: m_deployments.list_pages_builds,
  list_pr_comments: m_pull_requests.list_pr_comments,
  list_pr_files: m_pull_requests.list_pr_files,
  list_pr_reviews: m_pull_requests.list_pr_reviews,
  list_project_items: m_projects.list_project_items,
  list_refs: m_tags_refs.list_refs,
  list_release_assets: m_releases.list_release_assets,
  list_releases: m_releases.list_releases,
  list_repo_invitations: m_collaborators.list_repo_invitations,
  list_repo_secrets: m_secrets_and_variables.list_repo_secrets,
  list_repo_variables: m_secrets_and_variables.list_repo_variables,
  list_repo_webhooks: m_organization.list_repo_webhooks,
  list_repositories: m_base.list_repositories,
  list_tags: m_tags_refs.list_tags,
  list_team_members: m_organization.list_team_members,
  list_teams: m_organization.list_teams,
  list_workflow_jobs: m_actions.list_workflow_jobs,
  list_workflow_runs: m_actions.list_workflow_runs,
  list_workflows: m_actions.list_workflows,
  lock_issue: m_issues.lock_issue,
  manage_labels: m_issues.manage_labels,
  manage_milestones: m_issues.manage_milestones,
  merge_pull_request: m_pull_requests.merge_pull_request,
  remove_assignees: m_issues.remove_assignees,
  remove_collaborator: m_collaborators.remove_collaborator,
  remove_comment_reaction: m_reactions.remove_comment_reaction,
  remove_issue_reaction: m_reactions.remove_issue_reaction,
  remove_member_from_platform: m_membership.remove_member_from_platform,
  remove_org_member: m_organization.remove_org_member,
  remove_requested_reviewers: m_pull_requests.remove_requested_reviewers,
  remove_team_member: m_organization.remove_team_member,
  request_reviewers: m_pull_requests.request_reviewers,
  rerun_workflow: m_actions.rerun_workflow,
  search_code: m_base.search_code,
  search_issues: m_base.search_issues,
  set_branch_protection: m_repositories.set_branch_protection,
  transfer_repository: m_repositories.transfer_repository,
  trigger_pages_build: m_deployments.trigger_pages_build,
  trigger_workflow: m_actions.trigger_workflow,
  unlock_issue: m_issues.unlock_issue,
  update_issue: m_issues.update_issue,
  update_issue_comment: m_issues.update_issue_comment,
  update_project_item: m_projects.update_project_item,
  update_pull_request: m_pull_requests.update_pull_request,
  update_ref: m_tags_refs.update_ref,
  update_release: m_releases.update_release,
  update_repository: m_repositories.update_repository,
  update_webhook: m_organization.update_webhook,
} as const satisfies Record<string, DomainToolSpec>;
