// Compiles skill definitions into TypeScript manifests.
// Run: bun scripts/compile-skills.ts
import { readdir, readFile, mkdir, writeFile, access, unlink } from "node:fs/promises";
import { join } from "node:path";
import { parse as parseYAML } from "yaml";

const SKILLS_DIR = join(import.meta.dirname, "..", "src", "lib", "ai", "skills");
const TOOLS_DIR = join(import.meta.dirname, "..", "src", "lib", "ai", "tools");
const OUTPUT_DIR = join(SKILLS_DIR, "generated");

const SKILL_MENU_PLACEHOLDER = "{{SKILL_MENU}}";

const ROLE_MAP: Record<string, string> = {
  public: "UserRole.Public",
  organizer: "UserRole.Organizer",
  admin: "UserRole.Admin",
};

interface RawFrontmatter {
  name: string;
  description: string;
  criteria: string;
  tools: string[];
  minRole: string;
  mode: string;
  baseTools?: string[];
  routing?: string;
}

interface ParsedSkill {
  name: string;
  description: string;
  criteria: string;
  toolNames: string[];
  minRole: string;
  mode: string;
  instructions: string;
  /** Always-active discovery tools for a delegate domain (top-level skills only). */
  baseTools: string[];
  /** Cross-domain routing note rendered into the orchestrator's delegate docs. */
  routing?: string;
}

function parseFrontmatter(raw: string): { frontmatter: RawFrontmatter; body: string } {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error("Invalid SKILL.md: missing frontmatter delimiters");
  const frontmatter = parseYAML(match[1]) as RawFrontmatter;
  const body = match[2].trim();
  return { frontmatter, body };
}

async function readSkillFile(filePath: string): Promise<ParsedSkill> {
  const raw = await readFile(filePath, "utf-8");
  const { frontmatter, body } = parseFrontmatter(raw);

  if (!frontmatter.name || !frontmatter.description || !frontmatter.criteria) {
    throw new Error(
      `${filePath}: missing required frontmatter fields (name, description, criteria)`,
    );
  }
  const mode = frontmatter.mode ?? "inline";
  if (mode !== "inline" && mode !== "delegate") {
    throw new Error(
      `${filePath}: mode must be "inline" or "delegate", got ${JSON.stringify(mode)}`,
    );
  }
  // The runtime tool is named `loadSkill`; any "load_skill" mention would
  // point the model at a tool that doesn't exist.
  if (raw.includes("load_skill")) {
    throw new Error(`${filePath}: references "load_skill" — the tool is named "loadSkill"`);
  }

  return {
    name: frontmatter.name,
    description: frontmatter.description,
    criteria: frontmatter.criteria,
    toolNames: frontmatter.tools ?? [],
    minRole: frontmatter.minRole ?? "public",
    mode,
    instructions: body,
    baseTools: frontmatter.baseTools ?? [],
    routing: frontmatter.routing,
  };
}

/**
 * A `mode: delegate` top-level skill must carry everything the generated
 * domain registry needs — fail the build loudly instead of emitting a domain
 * the runtime can't wire up.
 */
async function validateDelegateSkill(dir: string, skill: ParsedSkill): Promise<void> {
  const filePath = join(SKILLS_DIR, dir, "SKILL.md");
  if (!skill.instructions.includes(SKILL_MENU_PLACEHOLDER)) {
    throw new Error(
      `${filePath}: delegate skill body must contain ${SKILL_MENU_PLACEHOLDER} ` +
        "(the role-filtered sub-skill menu is substituted there at runtime)",
    );
  }
  if (skill.baseTools.length === 0) {
    throw new Error(
      `${filePath}: delegate skill must declare baseTools ` +
        "(the always-active discovery tools for the subagent)",
    );
  }
  if (!(await pathExists(join(TOOLS_DIR, dir, "index.ts")))) {
    throw new Error(
      `${filePath}: delegate skill has no tool barrel at src/lib/ai/tools/${dir}/index.ts`,
    );
  }
}

function formatSkillEntry(key: string, s: ParsedSkill): string {
  const minRole = ROLE_MAP[s.minRole] ?? "UserRole.Public";
  const routing = s.routing === undefined ? "" : `\n    routing: ${JSON.stringify(s.routing)},`;
  return `  ${JSON.stringify(key)}: {
    name: ${JSON.stringify(s.name)},
    description: ${JSON.stringify(s.description)},
    criteria: ${JSON.stringify(s.criteria)},${routing}
    toolNames: ${JSON.stringify(s.toolNames)},
    minRole: ${minRole},
    mode: ${JSON.stringify(s.mode)},
    instructions: ${JSON.stringify(s.instructions)},
  }`;
}

function generateManifestFile(
  skills: Record<string, ParsedSkill>,
  enumsImport: string,
  typesImport: string,
): string {
  const entries = Object.entries(skills);
  if (entries.length === 0) {
    return `// Auto-generated by scripts/compile-skills.ts — do not edit.
import type { SkillBundle } from "${typesImport}";

export const SKILL_MANIFEST: Record<string, SkillBundle> = {};
`;
  }
  const lines = entries.map(([k, s]) => formatSkillEntry(k, s)).join(",\n");
  return `// Auto-generated by scripts/compile-skills.ts — do not edit.
import { UserRole } from "${enumsImport}";
import type { SkillBundle } from "${typesImport}";

export const SKILL_MANIFEST: Record<string, SkillBundle> = {
${lines},
};
`;
}

/** Valid JS identifier stem for a domain name (handles hyphens and leading digits). */
function identStem(domain: string): string {
  return domain.replace(/[^a-zA-Z0-9]/g, "_").replace(/^(?=[0-9])/, "_");
}

/** Uppercase identifier for a domain's manifest import alias, e.g. `GITHUB_SUBSKILLS`. */
function manifestAlias(domain: string): string {
  return `${identStem(domain).toUpperCase()}_SUBSKILLS`;
}

/** Identifier for a domain's tool-namespace import alias, e.g. `githubTools`. */
function toolsAlias(domain: string): string {
  return `${identStem(domain)}Tools`;
}

/**
 * The full domain registry: tool namespaces + sub-skill manifests +
 * base tool names. Importing it pulls in every domain's tool implementations,
 * so only runtime delegation code (delegates.ts) should consume it.
 */
function generateDomainsFile(domains: Record<string, ParsedSkill>): string {
  const names = Object.keys(domains);
  const manifestImports = names
    .map((d) => `import { SKILL_MANIFEST as ${manifestAlias(d)} } from "./domains/${d}.ts";`)
    .join("\n");
  const toolImports = names
    .map((d) => `import * as ${toolsAlias(d)} from "../../tools/${d}/index.ts";`)
    .join("\n");
  const entries = names
    .map(
      (d) => `  ${JSON.stringify(d)}: {
    tools: ${toolsAlias(d)} as unknown as ToolSet,
    subSkills: ${manifestAlias(d)},
    baseToolNames: ${JSON.stringify(domains[d].baseTools)},
  }`,
    )
    .join(",\n");
  return `// Auto-generated by scripts/compile-skills.ts — do not edit.
import type { ToolSet } from "ai";

import type { SkillBundle } from "../types.ts";

${toolImports}
${manifestImports}

export const DOMAINS: Record<
  string,
  { tools: ToolSet; subSkills: Record<string, SkillBundle>; baseToolNames: readonly string[] }
> = {
${entries},
};
`;
}

/**
 * Data-only domain → sub-skill manifest table (no tool imports), for
 * consumers like the context inspector that need sub-skill metadata without
 * coupling to tool implementations.
 */
function generateSubskillsFile(domainNames: string[]): string {
  const imports = domainNames
    .map((d) => `import { SKILL_MANIFEST as ${manifestAlias(d)} } from "./domains/${d}.ts";`)
    .join("\n");
  const entries = domainNames.map((d) => `  ${JSON.stringify(d)}: ${manifestAlias(d)}`).join(",\n");
  return `// Auto-generated by scripts/compile-skills.ts — do not edit.
import type { SkillBundle } from "../types.ts";

${imports}

export const DOMAIN_SUBSKILLS: Record<string, Record<string, SkillBundle>> = {
${entries},
};
`;
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

// Directories whose name starts with `_` are skipped — a lightweight way to
// disable a skill or sub-skill without deleting its files.
function isActiveSkillDir(name: string): boolean {
  return !name.startsWith("_");
}

async function main() {
  const topLevelEntries = await readdir(SKILLS_DIR, { withFileTypes: true });
  const skillDirs = topLevelEntries
    .filter((e) => e.isDirectory() && e.name !== "generated" && isActiveSkillDir(e.name))
    .map((e) => e.name)
    .sort();

  // ── Top-level skills (orchestrator manifest) ──
  const topSkills: Record<string, ParsedSkill> = {};
  for (const dir of skillDirs) {
    const filePath = join(SKILLS_DIR, dir, "SKILL.md");
    const skill = await readSkillFile(filePath);
    if (skill.mode === "delegate") await validateDelegateSkill(dir, skill);
    topSkills[dir] = skill;
  }

  await mkdir(OUTPUT_DIR, { recursive: true });
  await writeFile(
    join(OUTPUT_DIR, "manifest.ts"),
    generateManifestFile(topSkills, "../../constants.ts", "../types.ts"),
    "utf-8",
  );
  console.log(`Compiled ${Object.keys(topSkills).length} top-level skill(s) -> manifest.ts`);

  // ── Per-domain sub-skills (subagent manifests) ──
  const domainsDir = join(OUTPUT_DIR, "domains");
  await mkdir(domainsDir, { recursive: true });

  let subSkillCount = 0;
  const emittedDomainFiles = new Set<string>();
  for (const dir of skillDirs) {
    const subSkills: Record<string, ParsedSkill> = {};
    const subSkillsDir = join(SKILLS_DIR, dir, "skills");
    if (await pathExists(subSkillsDir)) {
      const subEntries = await readdir(subSkillsDir, { withFileTypes: true });
      const subDirs = subEntries
        .filter((e) => e.isDirectory() && isActiveSkillDir(e.name))
        .map((e) => e.name)
        .sort();
      for (const sub of subDirs) {
        subSkills[sub] = await readSkillFile(join(subSkillsDir, sub, "SKILL.md"));
      }
    }

    // Delegate domains always get a manifest file (even when empty) so the
    // generated domain tables can import them uniformly.
    if (Object.keys(subSkills).length === 0 && topSkills[dir].mode !== "delegate") continue;

    await writeFile(
      join(domainsDir, `${dir}.ts`),
      generateManifestFile(subSkills, "../../../constants.ts", "../../types.ts"),
      "utf-8",
    );
    emittedDomainFiles.add(`${dir}.ts`);
    subSkillCount += Object.keys(subSkills).length;
    console.log(`  ${dir}: ${Object.keys(subSkills).length} sub-skill(s)`);
  }

  // Drop manifests for domains that were deleted or renamed — stale files
  // would otherwise linger (the directory is gitignored, so only local
  // checkouts accumulate them) and confuse typecheck/knip.
  for (const file of await readdir(domainsDir)) {
    if (file.endsWith(".ts") && !emittedDomainFiles.has(file)) {
      await unlink(join(domainsDir, file));
      console.log(`  removed stale ${file}`);
    }
  }

  // ── Domain registries (delegate domains only) ──
  const delegates: Record<string, ParsedSkill> = {};
  for (const dir of skillDirs) {
    if (topSkills[dir].mode === "delegate") delegates[dir] = topSkills[dir];
  }
  await writeFile(join(OUTPUT_DIR, "domains.ts"), generateDomainsFile(delegates), "utf-8");
  await writeFile(
    join(OUTPUT_DIR, "subskills.ts"),
    generateSubskillsFile(Object.keys(delegates)),
    "utf-8",
  );
  console.log(
    `Compiled ${Object.keys(delegates).length} delegate domain(s) -> domains.ts, subskills.ts`,
  );

  console.log(`Total: ${Object.keys(topSkills).length} top-level + ${subSkillCount} sub-skills`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
