// Compiles skill definitions into TypeScript manifests.
// Run: bun scripts/compile-skills.ts
import { readdir, readFile, mkdir, writeFile, access } from "node:fs/promises";
import { join } from "node:path";
import { parse as parseYAML } from "yaml";

const SKILLS_DIR = join(import.meta.dirname, "..", "src", "lib", "ai", "skills");
const OUTPUT_DIR = join(SKILLS_DIR, "generated");

const ROLE_MAP: Record<string, string> = {
  public: "UserRole.Public",
  organizer: "UserRole.Organizer",
  admin: "UserRole.Admin",
};

interface RawFrontmatter {
  name: string;
  description: string;
  criteria: string;
  tools: string[];
  minRole: string;
  mode: string;
}

interface ParsedSkill {
  name: string;
  description: string;
  criteria: string;
  toolNames: string[];
  minRole: string;
  mode: string;
  instructions: string;
}

function parseFrontmatter(raw: string): { frontmatter: RawFrontmatter; body: string } {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error("Invalid SKILL.md: missing frontmatter delimiters");
  const frontmatter = parseYAML(match[1]) as RawFrontmatter;
  const body = match[2].trim();
  return { frontmatter, body };
}

async function readSkillFile(filePath: string): Promise<ParsedSkill> {
  const raw = await readFile(filePath, "utf-8");
  const { frontmatter, body } = parseFrontmatter(raw);

  if (!frontmatter.name || !frontmatter.description || !frontmatter.criteria) {
    throw new Error(
      `${filePath}: missing required frontmatter fields (name, description, criteria)`,
    );
  }

  return {
    name: frontmatter.name,
    description: frontmatter.description,
    criteria: frontmatter.criteria,
    toolNames: frontmatter.tools ?? [],
    minRole: frontmatter.minRole ?? "public",
    mode: frontmatter.mode ?? "inline",
    instructions: body,
  };
}

function formatSkillEntry(key: string, s: ParsedSkill): string {
  const minRole = ROLE_MAP[s.minRole] ?? "UserRole.Public";
  return `  ${JSON.stringify(key)}: {
    name: ${JSON.stringify(s.name)},
    description: ${JSON.stringify(s.description)},
    criteria: ${JSON.stringify(s.criteria)},
    toolNames: ${JSON.stringify(s.toolNames)},
    minRole: ${minRole},
    mode: ${JSON.stringify(s.mode)},
    instructions: ${JSON.stringify(s.instructions)},
  }`;
}

function generateManifestFile(
  skills: Record<string, ParsedSkill>,
  enumsImport: string,
  typesImport: string,
): string {
  const lines = Object.entries(skills)
    .map(([k, s]) => formatSkillEntry(k, s))
    .join(",\n");
  return `// Auto-generated by scripts/compile-skills.ts — do not edit.
import { UserRole } from "${enumsImport}";
import type { SkillBundle } from "${typesImport}";

export const SKILL_MANIFEST: Record<string, SkillBundle> = {
${lines},
};
`;
}

async function dirExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

// Directories whose name starts with `_` are skipped — a lightweight way to
// disable a skill or sub-skill without deleting its files.
function isActiveSkillDir(name: string): boolean {
  return !name.startsWith("_");
}

async function main() {
  const topLevelEntries = await readdir(SKILLS_DIR, { withFileTypes: true });
  const skillDirs = topLevelEntries
    .filter((e) => e.isDirectory() && e.name !== "generated" && isActiveSkillDir(e.name))
    .map((e) => e.name);

  // ── Top-level skills (orchestrator manifest) ──
  const topSkills: Record<string, ParsedSkill> = {};
  for (const dir of skillDirs) {
    const filePath = join(SKILLS_DIR, dir, "SKILL.md");
    topSkills[dir] = await readSkillFile(filePath);
  }

  await mkdir(OUTPUT_DIR, { recursive: true });
  await writeFile(
    join(OUTPUT_DIR, "manifest.ts"),
    generateManifestFile(topSkills, "../../constants.ts", "../types.ts"),
    "utf-8",
  );
  console.log(`Compiled ${Object.keys(topSkills).length} top-level skill(s) -> manifest.ts`);

  // ── Per-domain sub-skills (subagent manifests) ──
  const domainsDir = join(OUTPUT_DIR, "domains");
  await mkdir(domainsDir, { recursive: true });

  let subSkillCount = 0;
  for (const dir of skillDirs) {
    const subSkillsDir = join(SKILLS_DIR, dir, "skills");
    if (!(await dirExists(subSkillsDir))) continue;

    const subEntries = await readdir(subSkillsDir, { withFileTypes: true });
    const subDirs = subEntries
      .filter((e) => e.isDirectory() && isActiveSkillDir(e.name))
      .map((e) => e.name);
    if (subDirs.length === 0) continue;

    const subSkills: Record<string, ParsedSkill> = {};
    for (const sub of subDirs) {
      const filePath = join(subSkillsDir, sub, "SKILL.md");
      subSkills[sub] = await readSkillFile(filePath);
    }

    await writeFile(
      join(domainsDir, `${dir}.ts`),
      generateManifestFile(subSkills, "../../../constants.ts", "../../types.ts"),
      "utf-8",
    );
    subSkillCount += Object.keys(subSkills).length;
    console.log(`  ${dir}: ${Object.keys(subSkills).length} sub-skill(s)`);
  }

  console.log(`Total: ${Object.keys(topSkills).length} top-level + ${subSkillCount} sub-skills`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
