import matter from "gray-matter";
/**
 * Reads all SKILL.md and SYSTEM.md files under src/lib/ai/agents/
 * and generates a prompts/constants.ts barrel for each agent.
 *
 * Run with: bun scripts/generate-prompts.ts
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const AGENTS_DIR = join(import.meta.dirname, "../src/lib/ai/agents");

interface SkillData {
  name: string;
  description: string;
  criteria: string;
  instructions: string;
  toolNames: string[];
}

for (const agent of readdirSync(AGENTS_DIR, { withFileTypes: true })) {
  if (!agent.isDirectory()) continue;

  const promptsDir = join(AGENTS_DIR, agent.name, "prompts");
  const systemPath = join(promptsDir, "SYSTEM.md");
  const skillsDir = join(promptsDir, "skills");

  if (!existsSync(systemPath)) continue;

  const systemPrompt = readFileSync(systemPath, "utf-8");
  const skills: Record<string, SkillData> = {};

  if (existsSync(skillsDir)) {
    for (const skillDir of readdirSync(skillsDir, { withFileTypes: true })) {
      if (!skillDir.isDirectory()) continue;
      const skillPath = join(skillsDir, skillDir.name, "SKILL.md");
      if (!existsSync(skillPath)) continue;

      const raw = readFileSync(skillPath, "utf-8");
      const { data, content } = matter(raw);

      skills[skillDir.name] = {
        name: (data.name as string) ?? skillDir.name,
        description: (data.description as string) ?? "",
        criteria: (data.criteria as string) ?? "",
        instructions: content.trimStart(),
        toolNames: data.tools
          ? String(data.tools)
              .split(",")
              .map((t) => t.trim())
              .filter(Boolean)
          : [],
      };
    }
  }

  const skillEntries = Object.entries(skills)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, skill]) => {
      const escaped = (s: string) =>
        s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
      return `  ${JSON.stringify(key)}: {
    name: ${JSON.stringify(skill.name)},
    description: ${JSON.stringify(skill.description)},
    criteria: ${JSON.stringify(skill.criteria)},
    instructions: \`${escaped(skill.instructions)}\`,
    toolNames: ${JSON.stringify(skill.toolNames)},
  }`;
    })
    .join(",\n");

  const escapedSystem = systemPrompt
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

  const output = `// Auto-generated by scripts/generate-prompts.ts — do not edit manually.
// Re-generate with: bun scripts/generate-prompts.ts
import type { Skill } from "../../../context/types";

export const SYSTEM_PROMPT = \`${escapedSystem}\`;

export const SKILLS: Record<string, Skill> = {
${skillEntries}
};
`;

  const outPath = join(promptsDir, "constants.ts");
  writeFileSync(outPath, output);
  console.log(`Generated ${outPath} (${Object.keys(skills).length} skills)`);
}
