import { Env, makeEnv } from "@rayhanadev/env";

export const AppConfig = makeEnv("AppConfig", {
    DISCORD_CLIENT_ID: Env.string("DISCORD_CLIENT_ID"),
    DISCORD_BOT_TOKEN: Env.redacted("DISCORD_BOT_TOKEN"),
    GROQ_API_KEY: Env.redacted("GROQ_API_KEY"),
    GITHUB_TOKEN: Env.redacted("GITHUB_TOKEN"),
    MEDIAWIKI_BOT_KEY: Env.redacted("MEDIAWIKI_BOT_KEY"),
    PHACK_API_TOKEN: Env.redacted("PHACK_API_TOKEN"),
    PHONEBELL_OPEN_URL: Env.stringOr(
        "PHONEBELL_OPEN_URL",
        "https://api.purduehackers.com/phonebell/open",
    ),
    DASHBOARD_WS_URL: Env.stringOr("DASHBOARD_WS_URL", "ws://localhost:3001/discord/bot"),
    R2_ACCOUNT_ID: Env.string("R2_ACCOUNT_ID"),
    R2_ACCESS_KEY_ID: Env.redacted("R2_ACCESS_KEY_ID"),
    R2_SECRET_ACCESS_KEY: Env.redacted("R2_SECRET_ACCESS_KEY"),
    R2_BUCKET_NAME: Env.string("R2_BUCKET_NAME"),
    R2_PUBLIC_URL: Env.string("R2_PUBLIC_URL"),
    D1_ACCOUNT_ID: Env.string("D1_ACCOUNT_ID"),
    D1_DATABASE_ID: Env.string("D1_DATABASE_ID"),
    D1_API_TOKEN: Env.redacted("D1_API_TOKEN"),
    VERCEL_API_TOKEN: Env.redacted("VERCEL_API_TOKEN"),
    VERCEL_EDGE_CONFIG_ID: Env.string("VERCEL_EDGE_CONFIG_ID"),
    TZ: Env.stringOr("TZ", "America/Indiana/Indianapolis"),
    COMMIT_OVERFLOW_ENABLED: Env.booleanOr("COMMIT_OVERFLOW_ENABLED", false),
    DASHBOARD_ENABLED: Env.booleanOr("DASHBOARD_ENABLED", true),
    HACK_NIGHT_PHOTOS_ENABLED: Env.booleanOr("HACK_NIGHT_PHOTOS_ENABLED", true),
    AUTO_THREAD_ENABLED: Env.booleanOr("AUTO_THREAD_ENABLED", true),
    WELCOMER_ENABLED: Env.booleanOr("WELCOMER_ENABLED", true),
    NODE_ENV: Env.stringOr("NODE_ENV", "development"),
});
