import { createEnv } from "@t3-oss/env-core";
import { vercel } from "@t3-oss/env-core/presets-zod";
import { z } from "zod";

export const env = createEnv({
  server: {
    DISCORD_BOT_TOKEN: z.string(),
    DISCORD_BOT_CLIENT_ID: z.string(),
    DISCORD_BOT_PUBLIC_KEY: z.string(),
    CRON_SECRET: z.string(),
    LINEAR_API_KEY: z.string(),
    NOTION_TOKEN: z.string(),
    GITHUB_APP_ID: z.string(),
    GITHUB_APP_PRIVATE_KEY: z.string(),
    GITHUB_APP_INSTALLATION_ID: z.string(),
    GITHUB_ORG: z.string(),
    FIGMA_ACCESS_TOKEN: z.string(),
    FIGMA_TEAM_ID: z.string(),
    PHACK_ASK_API_KEY: z.string(),
    GROQ_API_KEY: z.string(),
    PHACK_API_TOKEN: z.string(),
    PHONEBELL_OPEN_URL: z.string(),
    DASHBOARD_URL: z.string(),
    PRIVACY_DB_URL: z.string(),
    PRIVACY_DB_API_KEY: z.string(),
    R2_ACCOUNT_ID: z.string(),
    R2_ACCESS_KEY_ID: z.string(),
    R2_SECRET_ACCESS_KEY: z.string(),
    EVENTS_R2_BUCKET_NAME: z.string(),
    SHIP_R2_BUCKET_NAME: z.string(),
    SHIP_DATABASE_TURSO_DATABASE_URL: z.string(),
    SHIP_DATABASE_TURSO_AUTH_TOKEN: z.string(),
    TURSO_DATABASE_URL: z.string(),
    TURSO_AUTH_TOKEN: z.string(),
    KV_REST_API_URL: z.string(),
    KV_REST_API_TOKEN: z.string(),
    VERCEL_API_TOKEN: z.string(),
    VERCEL_EDGE_CONFIG_ID: z.string(),
    EDGE_CONFIG: z.string(),
    SENTRY_AUTH_TOKEN: z.string(),
    SENTRY_ORG: z.string(),
    SENTRY_DSN: z.string().optional(),
    HCB_ORG_SLUG: z.string(),
    SERPAPI_API_KEY: z.string(),
    RESEND_API_KEY: z.string(),
    RESEND_WEBHOOK_SECRET: z.string(),
    HUNTER_API_KEY: z.string(),
    AI_GATEWAY_API_KEY: z.string(),
  },
  extends: [vercel()],
  runtimeEnv: process.env,
  skipValidation: process.env.SKIP_ENV_VALIDATION === "1",
});
